<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/150901/1-150Z1110953.jpg ",93,238);
$z[1][4]['ddimg']="/uploads/allimg/150901/1-150Z1110953.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="600";
$z[1][4]['height']="600";
$z[2]=Array("img"," /uploads/allimg/150901/1-150Z1110954.jpg ",240,386);
$z[2][4]['ddimg']="/uploads/allimg/150901/1-150Z1110954.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1174";
$z[2][4]['height']="980";

?>