<?php
$z[0]=Array("field","",441,460);
$z[0][4]['name']="title";
$z[1]=Array("global","",461,487);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",643,682);
$z[2][4]['filename']="header_m.htm";
$z[3]=Array("channel"," <a href=\"list.php?tid=[field:id/]\">[field:typename/]</a> ",799,995);
$z[3][4]['type']="son";
$z[3][4]['row']="10";
$z[3][4]['currentstyle']="<a href='list.php?tid=~id~' class='now' ~rel~><span>~typename~</span></a>";
$z[4]=Array("field","",1039,1058);
$z[4][4]['name']="title";
$z[5]=Array("field","",1071,1089);
$z[5][4]['name']="body";
$z[6]=Array("include","",1174,1213);
$z[6][4]['filename']="footer_m.htm";

?>