<dl class="news_dl">
        <dt><a href="[field:arcurl/]" target="_blank" title="[field:title/]"
                                    class="dt_1"> [[field:typename/]][field:title/]</a><span class="dt_2">[
          [field:pubdate function="MyDate('Y-m-d',@me)"/]
          ]</span>
              <div class="clear"></div>
            </dt>
        <dd> [field:description function='cn_substr(@me,220)'/]...</dd>
      </dl>