<?php
$z[0]=Array("global","",28,54);
$z[0][4]['name']="cfg_powerby";
$z[1]=Array("global","",75,96);
$z[1][4]['name']="cfg_dz";
$z[2]=Array("global","",288,310);
$z[2][4]['name']="cfg_tel";
$z[3]=Array("global","",462,483);
$z[3][4]['name']="cfg_qq";
$z[4]=Array("type","<a href=\"list.php?tid=[field:id/]\"><img src=\"/m/style/images/dblx.png\" width=\"30\" height=\"30\" /><br />\r\n      联系我们</a>",597,758);
$z[4][4]['typeid']="44";

?>