<?php
$z[0]=Array("channel"," <a href=\"[field:typeurl/]\">[field:typename/]</a> ",101,191);
$z[0][4]['type']="top";
$z[1]=Array("global","",381,407);
$z[1][4]['name']="cfg_powerby";
$z[2]=Array("global","",430,451);
$z[2][4]['name']="cfg_dz";
$z[3]=Array("global","",475,497);
$z[3][4]['name']="cfg_tel";
$z[4]=Array("global","",509,530);
$z[4][4]['name']="cfg_yx";
$z[5]=Array("global","",692,716);
$z[5][4]['name']="cfg_beian";
$z[6]=Array("global","",808,830);
$z[6][4]['name']="cfg_tel";
$z[7]=Array("flink","  [field:link /]  ",1140,1218);
$z[7][4]['titlelen']="20";
$z[7][4]['row']="20";
$z[7][4]['type']="text";

?>