<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,370);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",410,468);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",1150,1178);
$z[4][4]['name']="cfg_mobileurl";
$z[5]=Array("field","",1192,1208);
$z[5][4]['name']="id";
$z[6]=Array("global","",1677,1705);
$z[6][4]['name']="cfg_mobileurl";
$z[7]=Array("field","",1719,1735);
$z[7][4]['name']="id";
$z[8]=Array("include","",1851,1886);
$z[8][4]['filename']="head.htm";
$z[9]=Array("field","",2011,2040);
$z[9][4]['name']="position";
$z[10]=Array("type","\r\n        <li><a href=\"[field:typelink/]\" title=\"[field:typename/]\"> <img src=\"/skin/images/f[field:id/].jpg\" width=\"300\" height=\"185\" alt=\"[field:typename/]\" /></a>\r\n          <h5> <a href=\"[field:typelink/]\" title=\"[field:typename/]\"> [field:typename/]</a></h5>\r\n        </li>\r\n        ",2119,2442);
$z[10][4]['typeid']="29";
$z[11]=Array("type","\r\n        <li><a href=\"[field:typelink/]\" title=\"[field:typename/]\"> <img src=\"/skin/images/f[field:id/].jpg\" width=\"300\" height=\"185\" alt=\"[field:typename/]\" /></a>\r\n          <h5> <a href=\"[field:typelink/]\" title=\"[field:typename/]\"> [field:typename/]</a></h5>\r\n        </li>\r\n        ",2452,2775);
$z[11][4]['typeid']="30";
$z[12]=Array("type","\r\n        <li><a href=\"[field:typelink/]\" title=\"[field:typename/]\"> <img src=\"/skin/images/f[field:id/].jpg\" width=\"300\" height=\"185\" alt=\"[field:typename/]\" /></a>\r\n          <h5> <a href=\"[field:typelink/]\" title=\"[field:typename/]\"> [field:typename/]</a></h5>\r\n        </li>\r\n        ",2785,3108);
$z[12][4]['typeid']="31";
$z[13]=Array("type","\r\n        <li><a href=\"[field:typelink/]\" title=\"[field:typename/]\"> <img src=\"/skin/images/f[field:id/].jpg\" width=\"300\" height=\"185\" alt=\"[field:typename/]\" /></a>\r\n          <h5> <a href=\"[field:typelink/]\" title=\"[field:typename/]\"> [field:typename/]</a></h5>\r\n        </li>\r\n        ",3118,3441);
$z[13][4]['typeid']="32";
$z[14]=Array("type","\r\n        <li><a href=\"[field:typelink/]\" title=\"[field:typename/]\"> <img src=\"/skin/images/f[field:id/].jpg\" width=\"300\" height=\"185\" alt=\"[field:typename/]\" /></a>\r\n          <h5> <a href=\"[field:typelink/]\" title=\"[field:typename/]\"> [field:typename/]</a></h5>\r\n        </li>\r\n        ",3451,3774);
$z[14][4]['typeid']="33";
$z[15]=Array("include","",3862,3899);
$z[15][4]['filename']="footer.htm";

?>