<?php
$z[0]=Array("global","",92,113);
$z[0][4]['name']="cfg_gg";
$z[1]=Array("type"," <a href=\"[field:typelink/]\">关于我们</a>",137,217);
$z[1][4]['typeid']="24";
$z[2]=Array("type"," <a href=\"[field:typelink/]\">联系我们</a>",221,301);
$z[2][4]['typeid']="44";
$z[3]=Array("global","",499,525);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("global","",740,762);
$z[4][4]['name']="cfg_tel";
$z[5]=Array("channel","\r\n      <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n      ",922,1123);
$z[5][4]['type']="top";
$z[5][4]['currentstyle']="<li><a href='~typelink~' class='cur'>~typename~</a></li>";

?>