<?php
$z[0]=Array("field","",265,284);
$z[0][4]['name']="title";
$z[1]=Array("global","",285,311);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",352,381);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",421,479);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",1236,1264);
$z[4][4]['name']="cfg_mobileurl";
$z[5]=Array("field","",1278,1294);
$z[5][4]['name']="id";
$z[6]=Array("global","",1763,1791);
$z[6][4]['name']="cfg_mobileurl";
$z[7]=Array("field","",1805,1821);
$z[7][4]['name']="id";
$z[8]=Array("include","",1939,1974);
$z[8][4]['filename']="head.htm";
$z[9]=Array("include","",2172,2207);
$z[9][4]['filename']="left.htm";
$z[10]=Array("field","",2377,2406);
$z[10][4]['name']="position";
$z[11]=Array("list","\r\n    <dl class=\"dl_2s\">\r\n          <dt> <img src=\"[field:picname/]\" alt=\"[field:title/]\" /></dt>\r\n          <dd>\r\n        <h4> [field:title/]</h4>\r\n      </dd>\r\n        </dl>\r\n    ",2501,2718);
$z[11][4]['pagesize']="8";
$z[12]=Array("pagelist","",2798,2864);
$z[12][4]['listitem']="index,end,pre,next,pageno";
$z[12][4]['listsize']="5";
$z[13]=Array("arclist","\r\n    <dl class=\"product_dl_commend\">\r\n          <dt><a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:title/]\"> <img src=\"[field:picname/]\" alt=\"[field:title/]\" /></a></dt>\r\n          <dd> <a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:title/]\"> [field:title/]</a></dd>\r\n        </dl>\r\n    ",3055,3407);
$z[13][4]['row']="4";
$z[13][4]['typeid']="1";
$z[14]=Array("include","",3580,3617);
$z[14][4]['filename']="footer.htm";

?>