<?php
$z[0]=Array("field","",265,284);
$z[0][4]['name']="title";
$z[1]=Array("global","",285,311);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",352,381);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",421,479);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",1231,1259);
$z[4][4]['name']="cfg_mobileurl";
$z[5]=Array("field","",1273,1289);
$z[5][4]['name']="id";
$z[6]=Array("global","",1758,1786);
$z[6][4]['name']="cfg_mobileurl";
$z[7]=Array("field","",1800,1816);
$z[7][4]['name']="id";
$z[8]=Array("include","",1933,1968);
$z[8][4]['filename']="head.htm";
$z[9]=Array("include","",2165,2200);
$z[9][4]['filename']="left.htm";
$z[10]=Array("field","",2278,2307);
$z[10][4]['name']="position";
$z[11]=Array("list","\r\n      <dl class=\"p_list_dl\">\r\n    <dt><a href=\"[field:arcurl/]\" title=\"[field:title/]\"> <img src=\"[field:picname/]\" alt=\"[field:title/]\" title=\"[field:title/]\"\r\n                                width=\"180\" height=\"150\"></a></dt>\r\n    <dd>\r\n          <h5> <a href=\"[field:arcurl/]\" title=\"[field:title/]\"> [field:title/]</a></h5>\r\n        </dd>\r\n  </dl>\r\n      ",2369,2767);
$z[11][4]['pagesize']="12";
$z[12]=Array("arclist","\r\n    <li><span class=\"fr\"> [field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span><a target=\"_blank\"\r\n                                href=\"[field:arcurl/]\" title=\"[field:title/]\"> [field:title/]</a></li>\r\n    ",2912,3182);
$z[12][4]['titlelen']="60";
$z[12][4]['row']="20";
$z[12][4]['typeid']="34";
$z[13]=Array("include","",3359,3396);
$z[13][4]['filename']="footer.htm";

?>