<?php
$z[0]=Array("field","",441,460);
$z[0][4]['name']="title";
$z[1]=Array("global","",461,487);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",643,682);
$z[2][4]['filename']="header_m.htm";
$z[3]=Array("channel"," <a href=\"list.php?tid=[field:id/]\">[field:typename/]</a> ",799,995);
$z[3][4]['type']="son";
$z[3][4]['row']="10";
$z[3][4]['currentstyle']="<a href='list.php?tid=~id~' class='now' ~rel~><span>~typename~</span></a>";
$z[4]=Array("list","\r\n        <li><a href=\"view.php?aid=[field:id/]\">\r\n          <div class=\"lzj\"><img src=\"[field:litpic/]\"  /></div>\r\n          <h3>[field:title/]</h3>\r\n          <p>[field:description function='cn_substr(@me,60)'/]...</p>\r\n          </a> </li>\r\n        ",1082,1385);
$z[4][4]['pagesize']="30";
$z[4][4]['titlelen']="40";
$z[5]=Array("pagelist","",1502,1559);
$z[5][4]['listitem']="index,end,pageno";
$z[5][4]['listsize']="5";
$z[6]=Array("include","",1644,1683);
$z[6][4]['filename']="footer_m.htm";

?>